target("Runtime")
  set_kind("shared")
  set_runtimes("MDd")
  add_defines("PANDA_RUNTIME_API=PANDA_EXPORT","PANDA_RUNTIME_LOCAL=error")
  add_headerfiles("include/**.h",{install = false})
  add_files("src/**/build.*.c","src/**/build.*.cpp")
  add_includedirs("include",{public = true})
  add_includedirs("src",{public = true})
  add_includedirs("$(env VK_SDK_PATH)/Include",{public = true})